language: ruby

cache: bundler

sudo: false

rvm:
  - ruby-head
  - 2.5.1
  - 2.4.4
  - 2.3.6
  - 2.2.9

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head