language: ruby

cache: bundler

sudo: false

rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1
  - 1.9.3

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_3.2.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.0
      gemfile: gemfiles/rails_3.2.gemfile