language: ruby

cache: bundler

sudo: false

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1

gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile

matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/rails_5.1.gemfile
