language: ruby

cache: bundler

sudo: false

rvm:
  - ruby-head
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - 2.2.10

gemfile:
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_4.2.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head